server:
  port: 8080

#静态资源存放路径前缀
static-path:
  /www/server/nginx/html/backend/
ip:
  http://49.235.100.240:8080/

yuapi:
  client:
    access-key: 6pvaa8742g7bcdsh86k7hv9ci2yrhdci
    secret-key: oykm15xymum35dh19ehooc2bvjxuy4zh

spring:
  redis:
    host: 49.235.100.240
    port: 6379
    password: chenle123

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leo_blog?useSSL=false&allowPublicKeyRetrieval=True&allowReconnect=true
    username: root
    password: chenle123

  servlet:
    multipart:
      max-file-size: 20MB #单个文件最大为20M
      max-request-size: 20MB #单次请求文件总数大小为20M

logging:
  #项目日志路径
  level:
    com.chen.LeoBlog.dao: info
    com.chen.LeoBlog: info
  config: logback-config.xml
