server:
  servlet:
    context-path: /
  port: 8080


static-path:
  D:\\Javacode\\LeoBlog-back\\src\\main\\resources\\static\\
ip:
  http://localhost:8080/



#  静态资源
#  Path: src/main/resources/static
spring:
  redis:
    host: 49.235.100.240
    port: 6379
    password: chenle123






  #热部署相关
  devtools:
    restart:
      enabled: true
      poll-interval: 3000
      quiet-period: 1000
      additional-paths: src/main

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/leoblog?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=True
    url: jdbc:mysql://49.235.100.240:3306/leo_blog?useSSL=false&allowPublicKeyRetrieval=True&allowReconnect=true
    username: root
    password: chenle123

  servlet:
    multipart:
      max-file-size: 200MB #单个文件最大为20M
      max-request-size: 200MB #单次请求文件总数大小为20M

#mybatis:
#  mapper-locations: classpath:/mapper/*Mapper.xml
#  type-aliases-package: com.chen.LeoBlog.po

mybatis-plus:
    mapper-locations: classpath*:/mapper/**/*.xml
    type-aliases-package: com.chen.LeoBlog.po
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false
#      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  #项目日志路径
  level:
      com.chen.LeoBlog.dao: debug
      com.chen.LeoBlog: debug
  config: D:\Javacode\LeoBlog-back\src\main\resources\logback-config.xml



