server:
  port: 8080

  servlet:
    context-path: /

static-path:
  /www/server/nginx/html/backend/source/upload/images/

  #  静态资源
#  Path: src/main/resources/static
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: chenle123




  #  模板
  thymeleaf:
    cache: false
    prefix: classpath:/html/
    encoding: UTF-8 #编码
    suffix: .html #模板后缀
    mode: HTML #模板
    check-template: true #检查模板

  #热部署相关
  devtools:
    restart:
      enabled: true
      poll-interval: 3000
      quiet-period: 1000
      additional-paths: src/main/java

  datasource:
#    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/leoblog?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=True
    url: jdbc:mysql://localhost:3306/leo_blog?useSSL=false&allowPublicKeyRetrieval=True&allowReconnect=true
    username: root
    password: chenle123

  servlet:
    multipart:
      max-file-size: 2MB #单个文件最大为20M
      max-request-size: 20MB #单次请求文件总数大小为20M

#
#mybatis:
#  mapper-locations: classpath:/mapper/*.xml
#  type-aliases-package: com.chen.LeoBlog.po


mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.chen.LeoBlog.po
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
#      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  #项目日志路径
  level:
    #      com.chen.LeoBlog.dao: info
    com.chen.LeoBlog: info
  config: logback-config.xml
